export const CREATE_GAME_REQUEST = 'CREATE_GAME_REQUEST';
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';
export const CREATE_GAME_FAILURE = 'CREATE_GAME_FAILURE';

export const GET_GAME_BY_ID_REQUEST = 'GET_GAME_BY_ID_REQUEST';
export const GET_GAME_BY_ID_SUCCESS = 'GET_GAME_BY_ID_SUCCESS';
export const GET_GAME_BY_ID_FAILURE = 'GET_GAME_BY_ID_FAILURE';

export const UPDATE_GAME_SCORE_REQUEST = 'UPDATE_GAME_SCORE_REQUEST';
export const UPDATE_GAME_SCORE_SUCCESS = 'UPDATE_GAME_SCORE_SUCCESS';
export const UPDATE_GAME_SCORE_FAILURE = 'UPDATE_GAME_SCORE_FAILURE';